backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "data/productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "name", widget: "string" }
      - { label: "Precio", name: "price", widget: "number" }
      - { label: "Descripción", name: "desc", widget: "text" }
      - { label: "Imagen", name: "img", widget: "image" }
      - { label: "Categoría", name: "cat", widget: "string" }
