backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Precio", name: "price", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Categoría", name: "category", widget: "string" }
